/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planetfood.gui;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import planetfood.pojo.UserProfile;

/**
 *
 * @author hp
 */
public class AdminOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionFrame
     */
    public AdminOptionFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
       
        LblUser.setText("Hello "+UserProfile.getUserName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AddEmp = new javax.swing.JRadioButton();
        ViewEmp = new javax.swing.JRadioButton();
        EditEmp = new javax.swing.JRadioButton();
        RemoveEmp = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        RegisterCashier = new javax.swing.JRadioButton();
        RemoveCashier = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        ViewOrders = new javax.swing.JRadioButton();
        ViewDateWise = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        AddCategory = new javax.swing.JRadioButton();
        ViewCategory = new javax.swing.JRadioButton();
        EditCategory = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        AddProduct = new javax.swing.JRadioButton();
        ViewProduct = new javax.swing.JRadioButton();
        EditProduct = new javax.swing.JRadioButton();
        RemoveProduct = new javax.swing.JRadioButton();
        BtnShow = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnQuit = new javax.swing.JButton();
        LblUserName = new javax.swing.JLabel();
        LblLogOut = new javax.swing.JLabel();
        LblUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLANET FOOD ADMIN MENU");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Emp Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        AddEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(AddEmp);
        AddEmp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AddEmp.setForeground(new java.awt.Color(255, 255, 255));
        AddEmp.setText("Add Emp");
        AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpActionPerformed(evt);
            }
        });

        ViewEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(ViewEmp);
        ViewEmp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewEmp.setForeground(new java.awt.Color(255, 255, 255));
        ViewEmp.setText("View Emp");

        EditEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(EditEmp);
        EditEmp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EditEmp.setForeground(new java.awt.Color(255, 255, 255));
        EditEmp.setText("Edit Emp");

        RemoveEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(RemoveEmp);
        RemoveEmp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RemoveEmp.setForeground(new java.awt.Color(255, 255, 255));
        RemoveEmp.setText("Remove Emp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddEmp)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(RemoveEmp)
                        .addComponent(ViewEmp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EditEmp, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(AddEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ViewEmp)
                .addGap(18, 18, 18)
                .addComponent(EditEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoveEmp))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Cashier Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        RegisterCashier.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(RegisterCashier);
        RegisterCashier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegisterCashier.setForeground(new java.awt.Color(255, 255, 255));
        RegisterCashier.setText("Register Cashier");

        RemoveCashier.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(RemoveCashier);
        RemoveCashier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RemoveCashier.setForeground(new java.awt.Color(255, 255, 255));
        RemoveCashier.setText("Remove Cashier");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegisterCashier)
                    .addComponent(RemoveCashier))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterCashier)
                .addGap(18, 18, 18)
                .addComponent(RemoveCashier)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Report Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        ViewOrders.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(ViewOrders);
        ViewOrders.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        ViewOrders.setText("View Orders");

        ViewDateWise.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(ViewDateWise);
        ViewDateWise.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewDateWise.setForeground(new java.awt.Color(255, 255, 255));
        ViewDateWise.setText("View DateWise");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewDateWise)
                    .addComponent(ViewOrders))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ViewOrders)
                .addGap(18, 18, 18)
                .addComponent(ViewDateWise)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Category Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        AddCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(AddCategory);
        AddCategory.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AddCategory.setForeground(new java.awt.Color(255, 255, 255));
        AddCategory.setText("Add Category");
        AddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCategoryActionPerformed(evt);
            }
        });

        ViewCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(ViewCategory);
        ViewCategory.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewCategory.setForeground(new java.awt.Color(255, 255, 255));
        ViewCategory.setText("View Category");
        ViewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCategoryActionPerformed(evt);
            }
        });

        EditCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(EditCategory);
        EditCategory.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EditCategory.setForeground(new java.awt.Color(255, 255, 255));
        EditCategory.setText("Edit Category");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditCategory)
                    .addComponent(ViewCategory)
                    .addComponent(AddCategory))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddCategory)
                .addGap(18, 18, 18)
                .addComponent(EditCategory)
                .addGap(18, 18, 18)
                .addComponent(ViewCategory)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Product Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        AddProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(AddProduct);
        AddProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AddProduct.setForeground(new java.awt.Color(255, 255, 255));
        AddProduct.setText("Add Product");

        ViewProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(ViewProduct);
        ViewProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewProduct.setForeground(new java.awt.Color(255, 255, 255));
        ViewProduct.setText("View Product");

        EditProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(EditProduct);
        EditProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EditProduct.setForeground(new java.awt.Color(255, 255, 255));
        EditProduct.setText("Edit Product");

        RemoveProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(RemoveProduct);
        RemoveProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RemoveProduct.setForeground(new java.awt.Color(255, 255, 255));
        RemoveProduct.setText("Remove Product");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveProduct)
                    .addComponent(EditProduct)
                    .addComponent(ViewProduct)
                    .addComponent(AddProduct))
                .addGap(61, 61, 61))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(AddProduct)
                .addGap(18, 18, 18)
                .addComponent(ViewProduct)
                .addGap(18, 18, 18)
                .addComponent(EditProduct)
                .addGap(18, 18, 18)
                .addComponent(RemoveProduct)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        BtnShow.setBackground(new java.awt.Color(0, 102, 102));
        BtnShow.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnShow.setForeground(new java.awt.Color(255, 255, 255));
        BtnShow.setText("Show");
        BtnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShowActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAKE A CHOICE");

        BtnQuit.setBackground(new java.awt.Color(0, 102, 102));
        BtnQuit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnQuit.setForeground(new java.awt.Color(255, 255, 255));
        BtnQuit.setText("Quit");
        BtnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuitActionPerformed(evt);
            }
        });

        LblUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblUserName.setForeground(new java.awt.Color(255, 255, 255));

        LblLogOut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LblLogOut.setForeground(new java.awt.Color(255, 255, 255));
        LblLogOut.setText("LogOut");
        LblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblLogOutMouseExited(evt);
            }
        });

        LblUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LblUser.setForeground(new java.awt.Color(255, 255, 255));
        LblUser.setText("jLabel3");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\Admin_icon_2 (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblUserName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblLogOut)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblLogOut)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblUser)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnShow)
                    .addComponent(BtnQuit))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEmpActionPerformed

    private void ViewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewCategoryActionPerformed

    private void AddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCategoryActionPerformed

    private void BtnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShowActionPerformed

  String task = getOption();
  JFrame a = null;
  if (task == null) {
        JOptionPane.showMessageDialog(null, "Please Choose an Option", "Error!",JOptionPane.ERROR_MESSAGE);
            
  }
    if (task.equals("Add Product"))
         a= new AddProductFrame();
    if (task.equals("View Product"))
         a= new ViewProductFrame();
    if (task.equals("Add Emp"))
         a= new AddEmpFrame();
    if (task.equals("Edit Emp"))
         a= new EditEmpFrame();
    if (task.equals("View Products"))
        a = new ViewProductFrame();
    if (task.equals("Remove Emp"))
        a = new RemoveEmpFrame();
    if (task.equals("View Emp"))
        a= new ViewAllEmployeeFrame();
    if (task.equals("Register Cashier"))
       a= new RegisterCashierFrame();
     if (task.equals("Remove Cashier"))
       a= new RemoveCashierFrame();
      if (task.equals("View Orders"))
       a= new ViewAllDateOrderFrame();
       if (task.equals("View DateWise"))
       a= new ViewOrdersDatewiserFrame();
      if (task.equals("Add Category"))
       a= new AddCategoryFrame();
        if (task.equals("Edit Category"))
       a= new EditCategoryFrame();
      if (task.equals("View Category"))
       a= new ViewAllCategoriesFrame();
        if (task.equals("Edit Product"))
       a= new EditProductFrame();
          if (task.equals("Remove Product"))
       a= new RemoveProductFrame();
    a.setVisible(true);
        this.dispose();
  
    }//GEN-LAST:event_BtnShowActionPerformed
    private String getOption() {
        if (AddProduct.isSelected()) 
            return AddProduct.getText();
        else if(EditProduct.isSelected())
            return EditProduct.getText();
        else if(ViewProduct.isSelected())
            return ViewProduct.getText();
        else if (RemoveProduct.isSelected())
            return RemoveProduct.getText();
         else if (AddEmp.isSelected())
            return AddEmp.getText();
          else if (ViewEmp.isSelected())
            return ViewEmp.getText();
           else if (EditEmp.isSelected())
            return EditEmp.getText();
           else if (RemoveEmp.isSelected())
               return RemoveEmp.getText();
           else if (RegisterCashier.isSelected())
               return RegisterCashier.getText();
            else if (RemoveCashier.isSelected())
            return RemoveCashier.getText();
            else if (ViewOrders.isSelected())
                return ViewOrders.getText();
            else if(ViewDateWise.isSelected())
                return ViewDateWise.getText();
            else if (AddCategory.isSelected())
                return AddCategory.getText();
            else if (EditCategory.isSelected())
                return EditCategory.getText();
            else if (ViewCategory.isSelected())
                return ViewCategory.getText();
            
        else if (ViewEmp.isSelected())
                return ViewEmp.getText();
        else 
            return null;
        
    
}
    private void LblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblLogOutMouseEntered
       LblLogOut.setForeground(Color.yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_LblLogOutMouseEntered

    private void LblLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblLogOutMouseExited
        // TODO add your handling code here:
         LblLogOut.setForeground(Color.white);
    }//GEN-LAST:event_LblLogOutMouseExited

    private void LblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblLogOutMouseClicked
    UserLogInFrame opp = new UserLogInFrame();
        opp.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_LblLogOutMouseClicked

    private void BtnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuitActionPerformed
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AddCategory;
    private javax.swing.JRadioButton AddEmp;
    private javax.swing.JRadioButton AddProduct;
    private javax.swing.JButton BtnQuit;
    private javax.swing.JButton BtnShow;
    private javax.swing.JRadioButton EditCategory;
    private javax.swing.JRadioButton EditEmp;
    private javax.swing.JRadioButton EditProduct;
    private javax.swing.JLabel LblLogOut;
    private javax.swing.JLabel LblUser;
    private javax.swing.JLabel LblUserName;
    private javax.swing.JRadioButton RegisterCashier;
    private javax.swing.JRadioButton RemoveCashier;
    private javax.swing.JRadioButton RemoveEmp;
    private javax.swing.JRadioButton RemoveProduct;
    private javax.swing.JRadioButton ViewCategory;
    private javax.swing.JRadioButton ViewDateWise;
    private javax.swing.JRadioButton ViewEmp;
    private javax.swing.JRadioButton ViewOrders;
    private javax.swing.JRadioButton ViewProduct;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
